# Generated by Django 4.1.4 on 2023-02-15 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id_ciclo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('descripcionCiclo', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfileInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('siglasModulo', models.CharField(max_length=10, unique=True)),
                ('descripcionModulo', models.CharField(max_length=264, unique=True)),
                ('numRA', models.IntegerField()),
                ('arrayRACE', models.CharField(blank=True, max_length=200)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.ciclo')),
            ],
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id_act', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('numAct', models.IntegerField()),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.ciclo')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.modulo')),
            ],
        ),
    ]
