# Generated by Django 4.1.4 on 2023-02-01 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id_curso', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionCurso', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resultadosAprendizaje', models.CharField(max_length=10)),
                ('criteriosEvaluacion', models.CharField(max_length=10, null=True)),
                ('numActividades', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False)),
                ('siglasModulo', models.CharField(max_length=10, unique=True)),
                ('descripcionModulo', models.CharField(max_length=264, unique=True)),
                ('numRA', models.IntegerField(max_length=3)),
                ('numCE', models.IntegerField(max_length=3)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.curso')),
            ],
        ),
    ]
