# Generated by Django 4.1.4 on 2023-02-09 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciclo',
            fields=[
                ('id_ciclo', models.AutoField(primary_key=True, serialize=False)),
                ('descripcionCiclo', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id_modulo', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('siglasModulo', models.CharField(max_length=10, unique=True)),
                ('descripcionModulo', models.CharField(max_length=264, unique=True)),
                ('numRA', models.IntegerField()),
                ('numCE', models.IntegerField()),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.ciclo')),
            ],
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id_act', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('numAct', models.IntegerField()),
                ('n_RA_1', models.IntegerField(default=0)),
                ('n_CE_1', models.IntegerField(default=0)),
                ('n_RA_2', models.IntegerField(default=0)),
                ('n_CE_2', models.IntegerField(default=0)),
                ('n_RA_3', models.IntegerField(default=0)),
                ('n_CE_3', models.IntegerField(default=0)),
                ('n_RA_4', models.IntegerField(default=0)),
                ('n_CE_4', models.IntegerField(default=0)),
                ('n_RA_5', models.IntegerField(default=0)),
                ('n_CE_5', models.IntegerField(default=0)),
                ('n_RA_6', models.IntegerField(default=0)),
                ('n_CE_6', models.IntegerField(default=0)),
                ('n_RA_7', models.IntegerField(default=0)),
                ('n_CE_7', models.IntegerField(default=0)),
                ('n_RA_8', models.IntegerField(default=0)),
                ('n_CE_8', models.IntegerField(default=0)),
                ('n_RA_9', models.IntegerField(default=0)),
                ('n_CE_9', models.IntegerField(default=0)),
                ('n_RA_10', models.IntegerField(default=0)),
                ('n_CE_10', models.IntegerField(default=0)),
                ('ciclo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.ciclo')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.modulo')),
            ],
        ),
    ]
