# Generated by Django 4.1.4 on 2023-02-09 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciclo',
            name='id_ciclo',
            field=models.AutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
