# Generated by Django 4.1.4 on 2023-02-09 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='id_Ciclo',
        ),
    ]
