# Generated by Django 4.1.4 on 2023-02-01 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
