# Generated by Django 4.1.4 on 2023-02-01 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0002_delete_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='numCE',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='modulo',
            name='numRA',
            field=models.IntegerField(),
        ),
    ]
