# Generated by Django 4.1.4 on 2023-02-01 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0003_alter_modulo_numce_alter_modulo_numra'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Curso',
            new_name='Ciclo',
        ),
        migrations.RenameField(
            model_name='ciclo',
            old_name='descripcionCurso',
            new_name='descripcionCiclo',
        ),
        migrations.RenameField(
            model_name='ciclo',
            old_name='id_curso',
            new_name='id_ciclo',
        ),
        migrations.RenameField(
            model_name='modulo',
            old_name='curso',
            new_name='ciclo',
        ),
    ]
