# Generated by Django 4.1.4 on 2023-02-02 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0004_rename_curso_ciclo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numAct', models.IntegerField()),
                ('pesoCE1', models.IntegerField()),
                ('pesoCE2', models.IntegerField()),
                ('pesoCE3', models.IntegerField()),
                ('pesoCE4', models.IntegerField()),
                ('pesoCE5', models.IntegerField()),
                ('pesoCE6', models.IntegerField()),
                ('pesoCE7', models.IntegerField()),
                ('pesoCE8', models.IntegerField()),
                ('pesoCE9', models.IntegerField()),
                ('pesoCE10', models.IntegerField()),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calc_app.modulo')),
            ],
        ),
    ]
