# Generated by Django 4.1.4 on 2023-02-02 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0005_actividades'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='id_ciclo',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
