# Generated by Django 4.1.4 on 2023-02-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0008_remove_modulo_id_ciclo'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='id_ciclo',
            field=models.IntegerField(default=0),
        ),
    ]
