# Generated by Django 4.1.4 on 2023-02-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0009_modulo_id_ciclo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulo',
            name='id_ciclo',
            field=models.CharField(max_length=10),
        ),
    ]
