# Generated by Django 4.1.4 on 2023-02-02 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0010_alter_modulo_id_ciclo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modulo',
            name='id_ciclo',
        ),
    ]
